# Mybatis相关配置
mybatis:
  # 配置SQL语句的XML文件所在的位置
  mapper-locations: classpath:mapper/*.xml

#加载Spring Boot的情况下，日志的默认显示级别是info，只会显示此级别及更加重要的级别的日志info.warn,error
#为了所有日志都现在，包括trace(跟踪日志)，debug (调试日志)
#实际尝试有效
logging:
  level:
    com.luoyang.small: trace

# Knife4j配置
knife4j:
  # 开启增强模式 ,Spring 将使用bean来满足注入点的依赖关系
  enable: true

#解决Cannot invoke "PatternsRequestCondition.getPatterns()"
# Spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # jackson框架的相关配置
  jackson:
    # 服务器端响应JSON结果时，JSON结果中默认包含哪些属性
    #json所有属性为空是都不展示对应属性
    default-property-inclusion: non_null